//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatWebSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimda
    {
        public int ID { get; set; }
        public string Tarih { get; set; }
        public string Sehir { get; set; }
        public string Gorev { get; set; }
        public string Ozet { get; set; }
        public Nullable<bool> Tur { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
