//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatWebSitesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DogaYilmazEntities : DbContext
    {
        public DogaYilmazEntities()
            : base("name=DogaYilmazEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FaydaliLinkler> FaydaliLinkler { get; set; }
        public virtual DbSet<Hakkimda> Hakkimda { get; set; }
        public virtual DbSet<Hizmetlerimiz> Hizmetlerimiz { get; set; }
        public virtual DbSet<IletisimBilgileri> IletisimBilgileri { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<OfisSaatleri> OfisSaatleri { get; set; }
        public virtual DbSet<ProfYetkinveDiller> ProfYetkinveDiller { get; set; }
        public virtual DbSet<SosyalMedyalar> SosyalMedyalar { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
